# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources: 
  pipelines:
  - pipeline: "data"
    source: catnotcat.data
    trigger:
      branches:  
        include:  
        - master

pool: "Machine Learning"

# Build Model
stages:
- stage: buildmodel
  jobs:
  - job: 'BuildModel'
    pool: "Machine Learning"
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: "Download Training Data"
      inputs:
        buildType: 'current'
        artifactName: data
        targetPath: '$(System.DefaultWorkingDirectory)/data'
    - task: Bash@3
      displayName: 'Train Machine Model'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x train.sh
          ./train.sh
    - task: PublishPipelineArtifact@1
      displayName: "Publish Model"
      inputs:
        path: $(System.DefaultWorkingDirectory)/model.h5
        artifact: model
