# Used to convert Blob Storage data into a Pipeline Artifact

trigger: none
stages:
- stage: retrievedata
  jobs:
  - job: 'GetData'
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: AzureCLI@2
      displayName: 'Download Training Data'
      inputs:
        azureSubscription: 'Jason Personal AIRs Subscription(04fe963c-dced-4688-9372-1be7f86c986f)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          mkdir -p /var/shared/data/
          az storage blob download-batch -d /var/shared/data/ -s data --account-name catnotcat
    - task: PublishPipelineArtifact@1
      displayName: "Convert to Pipeline Artifact"
      inputs:
        path: /var/shared/data
        artifact: data
