# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - pipeline-model.yaml
      - train.sh
      - train.py

resources: 
  repositories:
   - repository: self
  pipelines:
  - pipeline: "data"
    source: catnotcat.data
    trigger:
      branches:  
        include:  
        - master

# Build Model
stages:
- stage: buildmodel
  jobs:
  - job: 'BuildModel'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: "Download Training Data"
      inputs:
        buildType: 'specific'
        project: 'd94fc176-cdf1-44e9-a9a2-5ef29d1d995c'
        definition: '7'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        targetPath: '$(System.DefaultWorkingDirectory)'
    - task: Bash@3
      displayName: 'Train Machine Model'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x train.sh
          ./train.sh
    - task: PublishPipelineArtifact@1
      displayName: "Publish Model"
      inputs:
        path: $(System.DefaultWorkingDirectory)/model.h5
        artifact: model
