# Builds the web api and trained model into a container

trigger: none

resources: 
  repositories:
   - repository: self
  pipelines:
  - pipeline: "model"
    source: catnotcat.model
    trigger:
      branches:  
        include:  
        - master

variables:
  dockerRegistryServiceConnection: '1282d892-cc76-4458-ad8d-bddcb35089c0'
  
stages:
- stage: Build
  displayName: 'Build and Push Container'
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'd94fc176-cdf1-44e9-a9a2-5ef29d1d995c'
        definition: '6'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        artifactName: 'model'
        targetPath: '$(Build.SourcesDirectory)'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'jasoncabotmscatnotcat'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
