apiVersion: v1
kind: Service
metadata:
  name: catnotcat
  namespace: prod
spec:
  selector:
    app: catnotcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: catnotcat
  namespace: staging
spec:
  selector:
    app: catnotcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: catnotcat
  namespace: dev
spec:
  selector:
    app: catnotcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP